# Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [6]:
import numpy as np
x = np.array([6, 10])
y = np.array([12, 5])
print("Original numbers:")
print(x)
print(y)

print("Comparison - greater : ")
print(np.greater(x, y))

print("Comparison - greater_equal : ")
print(np.greater_equal(x, y))

print("Comparison - less : ")
print(np.less(x, y))

print("Comparison - less_equal : ")
print(np.less_equal(x, y))

Original numbers:
[ 6 10]
[12  5]
Comparison - greater : 
[False  True]
Comparison - greater_equal : 
[False  True]
Comparison - less : 
[ True False]
Comparison - less_equal : 
[ True False]


# Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [5]:
import numpy as np

#Array of 10 zeros
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

#Array of 10 ones
array1=np.ones(10)
print("An array of 10 ones:")
print(array1)

#Array of 10 fives
array2=np.ones(10)*5
print("An array of 10 fives:")
print(array2)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array.

In [9]:
import numpy as np
x = np.array([[5,6],[7,8]])

#Let's Print Orignal Array
print("Original array:")
print(x)

#Sum of all elements
print("Sum of all elements:")
print(np.sum(x))

#Sum of each column
print("Sum of each column:")
print(np.sum(x, axis=0))

#Sum of each row
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[5 6]
 [7 8]]
Sum of all elements:
26
Sum of each column:
[12 14]
Sum of each row:
[11 15]


# Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [15]:
# add(), subtract(), multiply() and divide() 
  
import numpy as np
  
# initializing matrices 
x = np.array([[4, 3], [7, 5]]) 
y = np.array([[2, 9], [6, 8]]) 
  
# using add() to add matrices 
print ("The element wise addition of matrix is : ") 
print (np.add(x,y)) 
  
# using subtract() to subtract matrices 
print ("The element wise subtraction of matrix is : ") 
print (np.subtract(x,y)) 
  
# using multiply() to multiply matrices 
print ("The element wise multiplucation of matrix is : ") 
print (np.multiply(x,y)) 
    

# using divide() to divide matrices 
print ("The element wise division of matrix is : ") 
print (np.divide(x,y)) 

The element wise addition of matrix is : 
[[ 6 12]
 [13 13]]
The element wise subtraction of matrix is : 
[[ 2 -6]
 [ 1 -3]]
The element wise multiplucation of matrix is : 
[[ 8 27]
 [42 40]]
The element wise division of matrix is : 
[[2.         0.33333333]
 [1.16666667 0.625     ]]


# Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [17]:
import numpy as np

print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))


print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))


print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# Question 6:
Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [20]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anish', 'Dharam', 'Karinna', 'Jalay', 'Eshita', 'Mitesh', 'Mayank', 'Laukin', 'Keval', 'Jay'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)


      name  score  attempts qualify
a    Anish   12.5         1     yes
b   Dharam    9.0         3      no
c  Karinna   16.5         2     yes
d    Jalay    NaN         3      no
e   Eshita    9.0         2      no
f   Mitesh   20.0         3     yes
g   Mayank   14.5         1     yes
h   Laukin    NaN         1      no
i    Keval    8.0         2      no
j      Jay   19.0         1     yes


# Question 7:
Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [21]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anish', 'Dharam', 'Karinna', 'Jalay', 'Eshita', 'Mitesh', 'Mayank', 'Laukin', 'Keval', 'Jay'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("Select specific columns:")
print(df[['name', 'score']])


Select specific columns:
      name  score
a    Anish   12.5
b   Dharam    9.0
c  Karinna   16.5
d    Jalay    NaN
e   Eshita    9.0
f   Mitesh   20.0
g   Mayank   14.5
h   Laukin    NaN
i    Keval    8.0
j      Jay   19.0


# Question 8:
Write a Pandas program to join the two given dataframes along rows and assign all data.

In [23]:
import pandas as pd

student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Darshan Ingle', 'Rishabh Gandhi', 'Brijesh Patel', 'Bhavin Shah', 'Keval Patel'], 
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Saurabh Rana', 'Karan Shah', 'Dinesh Shah', 'Jalay Singh', 'Mayank Parmar'], 
        'marks': [201, 200, 198, 219, 201]})

print("Original DataFrames:")
print(student_data1)
print("-------------------------------------")
print(student_data2)
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([student_data1, student_data2])
print(result_data)


Original DataFrames:
  student_id            name  marks
0         S1   Darshan Ingle    200
1         S2  Rishabh Gandhi    210
2         S3   Brijesh Patel    190
3         S4     Bhavin Shah    222
4         S5     Keval Patel    199
-------------------------------------
  student_id           name  marks
0         S4   Saurabh Rana    201
1         S5     Karan Shah    200
2         S6    Dinesh Shah    198
3         S7    Jalay Singh    219
4         S8  Mayank Parmar    201

Join the said two dataframes along rows:
  student_id            name  marks
0         S1   Darshan Ingle    200
1         S2  Rishabh Gandhi    210
2         S3   Brijesh Patel    190
3         S4     Bhavin Shah    222
4         S5     Keval Patel    199
0         S4    Saurabh Rana    201
1         S5      Karan Shah    200
2         S6     Dinesh Shah    198
3         S7     Jalay Singh    219
4         S8   Mayank Parmar    201


# Question 9:
Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [28]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)

#pd.set_option('display.max_columns', None)

df = pd.DataFrame({
'order_no':[1001,np.nan,10002,10004,np.nan,10005,np.nan,10010,10003,10012,np.nan,10013],
'purch_amt':[1520,7065,6526,1105,4852,2408,5750,1983,24801,25045, 7529,3045],
'ord_date': ['2012-10-05','2012-09-10',np.nan,'2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3002,3001,3001,3003,3002,3001,3001,3004,3003,3002,3001,3001],
'employee_id':[3002,3003,3001,np.nan,3002,3001,3001,np.nan,3003,3002,3003,np.nan]})

print("Original Orders DataFrame:")
print(df)

print("\nMissing values of the said dataframe:")
print(df.isna())


Original Orders DataFrame:
    order_no  purch_amt    ord_date  customer_id  employee_id
0     1001.0       1520  2012-10-05         3002       3002.0
1        NaN       7065  2012-09-10         3001       3003.0
2    10002.0       6526         NaN         3001       3001.0
3    10004.0       1105  2012-08-17         3003          NaN
4        NaN       4852  2012-09-10         3002       3002.0
5    10005.0       2408  2012-07-27         3001       3001.0
6        NaN       5750  2012-09-10         3001       3001.0
7    10010.0       1983  2012-10-10         3004          NaN
8    10003.0      24801  2012-10-10         3003       3003.0
9    10012.0      25045  2012-06-27         3002       3002.0
10       NaN       7529  2012-08-17         3001       3003.0
11   10013.0       3045  2012-04-25         3001          NaN

Missing values of the said dataframe:
    order_no  purch_amt  ord_date  customer_id  employee_id
0      False      False     False        False        False
1       

# Question 10:
Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.

In [31]:
# import the library 
import pandas as pd 
  
# create the one-dimensional array 
data = [23, 25, 31, 36] 
  
# create the Series 
ex1 = pd.Series(data) 
  
# displaying the Series 
print(ex1) 

0    23
1    25
2    31
3    36
dtype: int64
